language: generic
git:
  depth: false
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
  - sudo apt-get update -y
  - sudo apt install -y libxml2 libxml2-utils python3-lxml google-cloud-sdk
  - openssl aes-256-cbc -K $encrypted_3565cb433837_key -iv $encrypted_3565cb433837_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar zxvf credentials.tar.gz
  - gcloud auth activate-service-account --key-file=client-secret.json
  - gcloud config set project opensiddur-client
  - ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine

script: ant test
after_script: ant docker-stop
